"""add phone column

Revision ID: 1f9f5b5dd46d
Revises: db58d360a989
Create Date: 2026-03-15 00:17:49.236004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f9f5b5dd46d'
down_revision: Union[str, Sequence[str], None] = 'db58d360a989'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("phone", sa.String()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "phone")
    # ### end Alembic commands ###
